version: '2'
services:
    myblog-app:
        image: myblog
        external_links:
            - myblog-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    myblog-mysql:
        extends:
            file: mysql.yml
            service: myblog-mysql
